### ISSUE TITLE
Bluetooth connection timeout if phone location disabled

### ISSUE THREAD

**Issue by ataffanel** [bitcraze/crazyflie-android-client#65] opened 2017-04-13 06:55 UTC
There has been one occurence where the bluetooth connection was always failing with a timeout if the android device location settings was disable: https://forum.bitcraze.io/viewtopic.php?f=2&t=2367&e=1&view=unread#p12015

In new android system bluetooth low energy is considered as a location technology so this makes sense but we should display a better error than connection timeout.

I haven't have time to confirm this on another device yet so, confirming the bug is the fist step.

**Comment by fredg02** [comment] 2017-04-14 15:43
Thanks for creating the bug, I will also try to reproduce the error. I have asked in the forum for a screenshot, because I'm not sure yet which exact setting is causing the error.

**Comment by fredg02** [comment] 2017-04-15 16:07
I cannot reproduce this error on a Nexus 5x with version 6.0.1 or 7.1.2. So I honestly don't know which "localization" or location settings is preventing the use of Bluetooth for the user.

**Comment by fredg02** [comment] 2017-05-19 22:35
After an extensive search and some tests this issue seems to be specific to the **HTC A9S**. There is currently no know way to reproduce this issue on another phone. Since a workaround has been found I have marked this as wontfix.

**Closed by fredg02** 2017-05-19 22:35 UTC
Labels: wontfix
